// Generated by https://jsonformatter.org/json-to-typescript

export type Config = {
  action: string;
  fp: number;
  fpt: number;
  tool: string;
  site: string;
  subtool: string;
  toolText: string;
  token: string;
  parentId: undefined;
  defaultOptions: DefaultOptions;
  fileLimits: Limits;
  allFileLimits: AllFileLimits;
  servers: string[];
  level: string;
  downloadUrl: string;
  user: undefined;
  country: string;
  dtr: boolean;
};

export type AllFileLimits = {
  limits: Limits;
  registered_limits: Limits;
  premium_limits: Limits;
  temp_limits: Record<string, Compress>;
};

export type Limits = {
  merge: Compress;
  split: Compress;
  compress: Compress;
  officepdf: Compress;
  wordpdf: Compress;
  powerpointpdf: Compress;
  excelpdf: Compress;
  pdfoffice: Compress;
  pdfword: Compress;
  pdfpowerpoint: Compress;
  pdfexcel: Pdfexcel;
  pdfjpg: Compress;
  imagepdf: Compress;
  pagenumber: Compress;
  watermark: Compress;
  rotate: Compress;
  unlock: Compress;
  protect: Compress;
  pdfa: Compress;
  repair: Compress;
  organize: Compress;
  resizeimage: Compress;
  compressimage: Compress;
  cropimage: Compress;
  converttojpg: Compress;
  convertfromjpg: Compress;
  rotateimage: Compress;
  watermarkimage: Compress;
  memeimage: Compress;
  editimage: Compress;
  editpdf: Compress;
  sign: Compress;
};

type Compress = {
  mb: number;
  files: number;
};

type Pdfexcel = {
  mb: number;
  files: number;
  pages: number;
};

type DefaultOptions = {
  output_filename: string;
  packaged_filename: string;
};
